name: CI

on:
  push:
    branches: [main, "feat/**"]
  pull_request:
    branches: [main, "feat/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  security-events: write
  contents: read

jobs:
  ci:
    name: Python CI
    uses: sebastienrousseau/pipelines/.github/workflows/python-ci.yml@cf0413f34ee0f24fe52a32f39d26eca513f65713
    with:
      python-version: '3.12'
      run-ruff: true
      run-mypy: true
      coverage-threshold: 100
      package-manager: 'poetry'
    secrets: inherit
